passwords:
    desktop:
        conor: ENC[AES256_GCM,data:ztoTPaRc416rlc8BQUuk1HRYan+VIeKi5jKY40JqziXIEgCcw0j0OMymh9O4b+mPRq7+WJGP+axyPZ3kqGzMQOcV93/akYYFQw==,iv:Z6waO6dv/ECEYp/bwCIDnpjRNt5wtMbywsmdU32MO+Q=,tag:QHQd6wv6CbAVxMIDBssiiQ==,type:str]
    vps:
        driver: ENC[AES256_GCM,data:qtRXNnV6RcDDBZDOuCTVJx/cCKqCfjwB8uBIprPFPuQ5fC/bOUt1IIGTLtBkitKjOT08UutUlJL5lIUCo+ECzkMCcYP0pLJZohnDAcW9lma7rzXzrDiCwo7WYs0TUI1F7RpiUJKGKirLOg==,iv:2XfzMTwk2eFS5lQNvSFp6eT/d0pnPY5sPJsDtuCKvKE=,tag:ky6alShhO37+3k9QgW+/vg==,type:str]
homeassistant:
    raise_lights: ENC[AES256_GCM,data:roQG6npN9hHL36//vorg8bRQ8w3iwSOopTexDu7B9o0aQ+0H+YDWdx6FkGDysZvOlUgWL83XyDKJpGprGADzAiPV30+xakUiatbRadUD,iv:47G3V+voqkFX9u0jx7sjfAyxKRetA7nG+wPydTgga+U=,tag:N+zl0UiOYtj+oL+ZOuqzXg==,type:str]
    dim_lights: ENC[AES256_GCM,data:ctuV7U1Oyt4FIvwsn5ADNjDL3qSsj/ytwqQJE3wBc+uujIs5cYGS0iY6eFk+BnqPhowmMYkeZuGgV0BsKKv+0IW2I2HR,iv:q3beg12entk+wJNhdXBZszJ2ovIrHCkDPfyzI4LFYbg=,tag:Pgj+/bfVDSVeEX9mNJQILQ==,type:str]
sops:
    age:
        - recipient: age14e20tgvtrz442g09juqgrwfat8adty0wgqqgule9ts3w23c88d2qqya03l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSzhubUEvMXlYaXlBQnEv
            dXVyZW5mcFl4NmpEaFcvMk4xa1lFQml2cXp3ClplbnpzQXJQT3dRMmduOHNhamtN
            TDlUaWE0MkFEdEZ3QjBaZDB2VHR0dEkKLS0tIFBXRTVrajJGbm5qT1lzSGh1TTcz
            T2hnaStTdjUrZy8rQjFLK0ZHYTNIMDQK7py1sgd8rOqaZ8SlmjSRRAsLOmO2GbyJ
            FqIC4AIV3mVLJ8nvviNbnJyerMEr+ETD4OIKPY7FGVFhHvoG3cPX5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w9kt3da02kxv2q7e6m9elhkqdqxqgxnmj647qzsygyrsuk4xzpwqjmpmfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa012dE14VDN2T2k5T1F4
            UWt2bkpaRzdNV2syRm44VXRIYmtlSFdOUFVFCkdheUtaakdwNkdTeVpQTWMvZW0v
            QkQ2T1lTb3h0aGd0ZHdzRDFtZlc2L1kKLS0tIGx6S3Y2QlBaRFNzcXg4S2dpNGg1
            UWdBVnZFdGpxR3VwaDRhOTZXYlVVdEUK+eJlVtrf3xSZzPKb+V/OppRVIsRKSTjC
            aefhwzax+epFSkugWPtRA8i8XQGWu6/3IpAp8jYGu/zYoTX0o61ELA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T22:00:19Z"
    mac: ENC[AES256_GCM,data:Vow6uP8kDse0uLzMH1Has80cxx0sAd3hoh2noowM6heZq6DWg5Ir4r7K6cQfeyqjb80LyQU1gutvBkOCM5zTM/cihAzFTDLXztHnm721XNnk4AYnSDAjoi9qcB8uIGXTRgBGwuFPgJ/IvHexmZ8IKC55TVuxRyLDevEso4JTPKw=,iv:bv9iscgNI8rVgYupWwMf8EH8W/D+YPVKRwQs9xUvLMM=,tag:NsMG3CoIyvRdHmcU8ao7dA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
